Repository dusk-network/rusk-vm, pull requests merged in 2022-06, with the labels that each got.

#358 Upgrade Wasmer dependency from 2.0.0 to 2.3
  Cargo.toml
  rusk-uplink/Cargo.toml
  src/compiler_config.rs
  tests/contracts/block_height/Cargo.toml
  tests/contracts/callee-1/Cargo.toml
  tests/contracts/callee-2/Cargo.toml
  tests/contracts/caller/Cargo.toml
  tests/contracts/counter/Cargo.toml
  tests/contracts/delegator/Cargo.toml
  tests/contracts/fibonacci/Cargo.toml
  tests/contracts/gas_consumed/Cargo.toml
  tests/contracts/gas_context/Cargo.toml
  tests/contracts/minimal_counter/Cargo.toml
  tests/contracts/register/Cargo.toml
  tests/contracts/self_snapshot/Cargo.toml
  tests/contracts/stack/Cargo.toml
  tests/contracts/stack/src/lib.rs
  tests/contracts/string_argument/Cargo.toml
  tests/contracts/tx_vec/Cargo.toml
Labels: team:Core, mark:next

#359 Event system implementation
  Cargo.toml
  rusk-uplink/src/definitions.rs
  rusk-uplink/src/hosted.rs
  src/call_context.rs
  src/ops/emit.rs
  src/ops/mod.rs
  src/resolver.rs
  src/state.rs
  tests/contracts/events/Cargo.toml
  tests/contracts/events/Makefile
  tests/contracts/events/rustfmt.toml
  tests/contracts/events/src/lib.rs
  tests/contracts/stack/src/lib.rs
  tests/dual_test.rs
  tests/gas_context.rs
  tests/lib.rs
Labels: type:feature, team:Core

#361 VM2 error related improvements
  rusk-uplink/src/definitions.rs
  src/call_context.rs
  src/error.rs
  src/lib.rs
  src/modules.rs
  src/ops/panic.rs
  src/state.rs
  src/state/persist.rs
  tests/lib.rs
Labels: team:Core, mark:next

#365 Fix `kcov` to fail when tests fail
  .github/workflows/dusk_ci.yml
Labels: team:Core

#366 VM2 hash
  rusk-uplink/Cargo.toml
  rusk-uplink/src/helpers.rs
  src/modules.rs
  src/state.rs
  tests/gas_usage.rs
  tests/stack.rs
Labels: team:Core, mark:next

#369 Place both contract code and state behind link
  CHANGELOG.md
  src/call_context.rs
  src/contract.rs
  src/lib.rs
  src/state.rs
  test_runner/src/main.rs
Labels: type:tech-debt, team:Core

#368 Forward port `dusk-hamt` test
  Cargo.toml
  tests/contracts/map/Cargo.toml
  tests/contracts/map/Makefile
  tests/contracts/map/rustfmt.toml
  tests/contracts/map/src/lib.rs
  tests/lib.rs
Labels: type:tech-debt, team:Core

#375 Refactor configuration to be static per instance
  CHANGELOG.md
  src/call_context.rs
  src/compiler.rs
  src/compiler_config.rs
  src/config.rs
  src/lib.rs
  src/modules.rs
  src/state.rs
  src/state/persist.rs
  tests/configuration.rs
  tests/gas_usage.rs
Labels: team:Core
